name = "wangpedersen-site"
type = 'webpack'
account_id = ''
routes = ['wangpedersen.com/*', 'www.wangpedersen.com/*']
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"
site = {bucket = "site",entry-point = "workers-site"}
